name:                url-shortener
version:             0.1.0.0
github:              "m-schm/url-shortener"
license:             BSD3
author:              "m-schm"
copyright:           "2021 m-schm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/url-shortener#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5 && < 2
- bytestring >= 0.10 && < 2
- monad-logger >= 0.3 && < 1
- mtl >= 2.2 && < 3
- persistent >= 2.11 && < 3
- persistent-postgresql >= 2.11 && < 3
- persistent-template >= 2.9 && < 3
- servant-server >= 0.18 && < 1
- text >= 1.2 && < 2

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
- DataKinds
- DerivingStrategies
- FlexibleContexts
- GeneralizedNewtypeDeriving
- InstanceSigs
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- UnicodeSyntax

executables:
  url-shortener-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - url-shortener
    - warp >= 3.3 && < 4

tests:
  url-shortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortener
